### ISSUE TITLE
pod link on dependencies doesn't work

### ISSUE THREAD

**Issue by hfossli** [mowens/cocoapods-links#3]
In order for the plugin to work on dependencies I need to add them to the podfile

```
pod 'foo'
```

It would be awesome to be able to link dependencies as well.

**Comment by mowens** [comment]
Sorry for such a long delay on a response. Are you referring to linking dependencies in your podspec that are not defined in the Podfile itself? That isn't something that is supported at the moment as the links only hooks the `pod Foo` command. So the pod has to be defined in the Podfile in order to leverage the link.

**Comment by hfossli** [comment]
I see. That's what I thought.
